blank_issues_enabled: false
contact_links:
  - name: Contribuire tramite ingegnerismo.it
    url: https://ingegnerismo.it/contribuisci/
    about: Contatta la redazione se non vuoi o non puoi usare GitHub.
